### ISSUE TITLE
Just a suggesion.

### ISSUE THREAD

**Issue by brandonplank** [LinusHenze/Fugu#18]
If it would be at all possible, would you allow be access to https://repo.fugujb.dev/bootstrap so i could update everything to include https://github.com/coolstar/Odyssey-bootstrap, i will also be willing to make a pr with the changes needed for it to work. Thanks in advance

**Comment by LinusHenze** [comment]
Of course! The repo is now public. You can find it here: https://github.com/LinusHenze/Fugu-Repo
