### ISSUE TITLE
iPhone 7 (gold) stuck on white screen during boot.

### ISSUE THREAD

**Issue by XanDesign** [LinusHenze/Fugu#2]
My iphone 7 is getting stuck on a white screen after running ./Fugu iStrap. Pretty sure this is happening whilst the verbose style boot screen should appear.

**Comment by LinusHenze** [comment]
Could you try commenting out the following lines in iStrap/iStrap/main.c:
findAppleLogo(&lgStartX, &lgStartY, &lgEndX, &lgEndY);
checkerboardInterleaved(lgStartX, lgStartY, lgEndX, lgEndY, fb[0]);

It could be that the functions for finding and coloring the Apple logo do not work on devices with a white boot screen.

**Comment by LinusHenze** [comment]
Should be fixed now.
Could you (or someone with a white/gold iPhone 7) please try the updated v0.2 release?

**Comment by LinusHenze** [comment]
Confirmed to be fixed, therefore I'm closing the issue.
