### ISSUE TITLE
Remove bingers repo

### ISSUE THREAD

**Issue by brandonplank** [LinusHenze/Fugu#7]
Remove his repo as this causes issue with the jailbreak, and will detect it as checkra1n

also. instead of adding the chimera source to the sileo.list

/etc/apt/sources.list.d/chimera.sources is the file

you'll want to add this as the contents:

Types: deb
URIs: https://repo.chimera.sh
Suites: ./
Components:

this causes the Sileo post install script to detect it as a chimera jailbreak, thus causing no issues.

**Comment by brandonplank** [comment]
Also, Add snappy to add a system snapshot so the jailbreak will persist

snappy -f / -r $(snappy -f / -l | sed -n 2p) -t orig-fs

**Comment by coolstar** [comment]
👍 to this. Sileo's postinst checks for either the presence of /etc/apt/sources.list.d/chimera.sources or /etc/apt/sources.list.d/electra.list (chimera.sources is preferred as it is the newer of the 2 repos and is also the newer debian format)

**Comment by Crypto-Light** [comment]
Hi, i can't be able to delete bingners repo! I delete the repo in the file but it returns!!! Why?
There are 12 updates to do and 23 pending installing....
Core Utilities and Core Utilities (/bin) can't be able to install.

What can i do for fixing it?

Thanks.
Thanks.

**Comment by LinusHenze** [comment]
Should be fixed now. Thank you @brandonplank for telling me how to rename the snapshot!
